<h2><i class="fa fa-home"></i> Accueil</h2>
<!-- Liste des articles du blog -->
<ul class="post-list">
    <?php foreach ($thePosts as $key => $value ) {?>
    <li class="post">
        <h3><i class="fa fa-hand-o-right"></i>&nbsp;
        <a href="post.php?id=<?=$value['post_id'] ?>" title="Consulter l'article"><?=$value['post_title']?></a>
        </h3>
        <ul>

        <article>
            <?php if (strlen($value['post_content'])>50){
                $contentShort = substr($value['post_content'], 0, 50);
                echo $contentShort;
            }
            else{
                echo $value['post_content'];
            };?> [...]</article>

        <small>Rédigé par <?= $value['author_firstName']?> <?= $value['author_lastName']?>, le <?=$value['post_dateCreation']?></small>
        </li>
        <?php } ?>
    </ul>                     