<fieldset>
	<form action="register.php" method="post">
		<ul>
			<li>
			<label for="lastName">Nom :</label>
		    <input type="text" placeholder="nom" name='lastName'>
		    </li>
		    <li>
		    <label for="firstName">Prénom:</label>
		    <input type="text" placeholder="prénom" name='firstName'>
		    </li>
		    <li>
		    <label for="pseudo">Pseudo:</label>
		    <input type="text" placeholder="pseudo" name='pseudo'>
		    </li>
		    <li>
		    <label for="mail">Adresse mail:</label>
		    <input type="text" placeholder="mail" name='mail'>
		    </li>
		    <li>
		    <label for="password">Mot de Pass:</label>
		    <input type="text" placeholder="password" name='password'>
		    </li>
		    <button type="submit" name="submit" >Enregistrer</button>
		</ul>
	</form>
</fieldset>

