<h2><i class="fa fa-file-text-o"></i> Article</h2>

<section class="post">
    <h3><?= htmlspecialchars($post['Title']) ?></h3>
    <article><?= nl2br(htmlspecialchars($post['Contents'])) ?></article>
    <small>
        Rédigé par <?= htmlspecialchars($post['FirstName']) ?> <?= htmlspecialchars($post['LastName']) ?>
        le <?= htmlspecialchars($post['CreationDate']) ?>
    </small>
</section>

<hr>


<form class="generic-form" action="add_comment.php" method="POST">

    <input type="hidden" name="postId" value="<?= $_GET['id'] ?>">

    <fieldset>
        <legend><i class="fa fa-comment-o"></i> Nouveau commentaire</legend>
        <ul>
            <li>
                <label for="nickName">Pseudo :</label>
                <input type="text" id="nickName" name="nickName">
            </li>
            <li>
                <label class="textarea" for="contents">Commentaire :</label>
                <textarea id="contents" name="contents" rows="5"></textarea>
            </li>
            <li>
                <button class="button button-primary" type="submit">Ajouter</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>
