<!DOCTYPE html>
<html lang="fr">
	<head>
	 <title>INDEX PHP</title>
    <meta charset="utf-8">
 	</head>
 	 	<header>
 	 		<h1>Traducteur Anglais-Français</h1>
 	 	</header>
 	 	<main>
 
      	</main>
      	<div class="searchbar">
      		<form method="POST" action= "exercicetrad.php">
      			<label for="mot">Mot:</label>
      			<input class='champ' type='text' name="mot" value""/>
      		</form>
      	</div>
      	<p>
			<legend>Sens de traduction :</legend>
			<select name="choix">
			<option value="toFrench">Anglais vers français</option>
			<option value="toEnglish"> françaisvers Anglais</option>
			</select>
		</p>
		<div class="button">
  			 <button type="traduction">Traduire</button>
  		</div>

<body>
</body>
</html>