<!DOCTYPE html>
<html>
   <head>
      <title>index</title>
      </head>
      <body>
      	<div>
            <nav>
                <a href="exemple2.php">Home</a>
                <a href="forme.php">lien vers le formulaire</a>
                <a href="get.php?name=Paul&id=32>lien vers let get de Paul"</a>
                <a href="get.php?name=Jacques&id=14">lien vers le get de Jacques</a>
                <a href="get.php?name=Pierre&id=39">lien vers le get de Pierre</a>
            </nav>
            <p> Je suis le header</p>
        

		</div>